### ISSUE TITLE
N00b Question - Can this be used to change Swift Version used by Xcode?

### ISSUE THREAD

**Issue by jeffreybergier** [neonichu/chswift#11]
Hi, total N00b question. I really want to work in Xcode 7 with the new SDK's, but the project I'm working on has frameworks that can only be built with Swift 1.2. So even though I can upgrade my code easily to swift 2.0, the frameworks are holding me back.

Can this tool be used to force Xcode 7 to use swift 1.2 when building and editing or is chswift meant for a different purpose?

**Comment by neonichu** [comment]
Unfortunately, it cannot. The purpose is entirely focused on changing the version of Xcode, and therefore Swift, to be used in your current terminal session.
