### ISSUE TITLE
Append `swift-` as a prefix to swift versions

### ISSUE THREAD

**Issue by kylef** [neonichu/chswift#15]
We discussed this on iMessage, but just wanted to file an issue so we don't forget.
##### Changes

Versions should be prefixed by the implementation (usually `swift`) followed by a dash. For backwards compatibility, chswift may allow automatically prepending `swift-` when the version doesn't have an implementation.
##### Justification

This is more consistent with other `-version` type files and more forwards thinking. There can and may be alternative implementations of Swift in the future.

Examples:
- Ruby (`jruby-1.6.8`)
- Python (`pypy-3.2.5`)
- Node (`iojs-0.12`)

**Comment by neonichu** [comment]
As of 0.3.0, `chswift` at least supports a _swift-_ prefix and also development snapshot suffixes. However, it does not take it into account for selection.
