### ISSUE TITLE
Ability to use directly for a specific version

### ISSUE THREAD

**Issue by kylef** [neonichu/chswift#2]
I.e, 'chswift1.2' should envoke `swift` 1.2 or error if unavailable. This means it can be used in Swift scripts requiring a specific version:

``` swift
#!/usr/bin/env chswift1.2

println("Hello Swift World.")
```

**Comment by neonichu** [comment]
This has been solved by https://github.com/neonichu/cato:

``` bash
#!/usr/bin/env cato 1.2

println("Hello Swift World.")
```
