### ISSUE TITLE
Doesn't parse Xcode's with spaces in their names.

### ISSUE THREAD

**Issue by danthorpe** [neonichu/chswift#4]
For example, because Xcode is packaged as `Xcode-beta.app` many developers (especially those with OCD) are likely to rename this to say `Xcode 6.3b4.app` as it is wise to not delete the previous beta until the new one is considered stable enough to use. Additionally, Apple have had betas of different Xcode versions (6.2 & 6.3) available simultaneously.

Unfortunately, these Xcode's are not successfully discovered - and my bash fu is not good enough to figure out how to escape the spaces properly...

**Comment by neonichu** [comment]
Fixed in 4333ccec35e8e39084fc5079c6d6657e6f5b3554 - thanks for reporting!
