### ISSUE TITLE
Documentation for .swift-version file formats

### ISSUE THREAD

**Issue by ashfurrow** [neonichu/chswift#7]
Missing in readme. I'd add it but I'm about to board a plane.

**Comment by neonichu** [comment]
There's 

``` bash
$ echo 1.2 >.swift-version
```

in the README - not sure what else is needed :)

**Comment by ashfurrow** [comment]
Must've missed that. Could use a sentence saying "the file should just contact the version you want, so use..."

**Comment by ashfurrow** [comment]
I'll submit a pr.

**Comment by neonichu** [comment]
:sparkling_heart:
